/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * User-facing configuration for request processing with budget percentages.
 * CancellationToken for cancelling async operations
 */
export declare class CancellationToken {
  /** Create a new cancellation token */
  constructor()
  /** Cancel all operations using this token */
  cancel(): void
  /** Check if cancellation has been requested */
  get isCancelled(): boolean
}
/** Provides sensible defaults and getters for all properties. */
export declare class RequestProcessingPreference {
  constructor(maxConcurrentRequests?: number | undefined | null, batchSize?: number | undefined | null, timeoutS?: number | undefined | null, maxCharsPerRequest?: number | undefined | null, pinInitialEndpointOnce?: boolean | undefined | null, hedgeDelay?: number | undefined | null, totalTimeoutS?: number | undefined | null, hedgeBudgetPct?: number | undefined | null, retryBudgetPct?: number | undefined | null, maxRetries?: number | undefined | null, initialBackoffMs?: number | undefined | null, cancelToken?: CancellationToken | undefined | null, primaryApiKeyOverride?: string | undefined | null, extraHeaders?: Record<string, string> | undefined | null, nonRetryableStatusCodes?: Array<number> | undefined | null, traceparent?: string | undefined | null, tracestate?: string | undefined | null)
  get maxConcurrentRequests(): number
  get batchSize(): number
  get timeoutS(): number
  get maxCharsPerRequest(): number | null
  get hedgeDelay(): number | null
  get pinInitialEndpointOnce(): boolean
  get totalTimeoutS(): number | null
  get hedgeBudgetPct(): number
  get retryBudgetPct(): number
  get maxRetries(): number
  get initialBackoffMs(): number
  get primaryApiKeyOverride(): string | null
  get extraHeaders(): Record<string, string> | null
  get nonRetryableStatusCodes(): Array<number>
  get traceparent(): string | null
  get tracestate(): string | null
  /**
   * Whether this preference already names the call's parent, in `traceparent` or in
   * `extraHeaders`; the package entry point then leaves the active span alone.
   */
  get hasExplicitTraceContext(): boolean
  /** A copy of this preference whose calls join the given trace context. */
  withTraceContext(traceparent: string, tracestate?: string | undefined | null): RequestProcessingPreference
}
export declare class HttpClientWrapper {
  constructor(httpVersion?: number | undefined | null, proxy?: string | undefined | null)
}
export declare class Endpoint {
  constructor(baseUrl: string, apiKey: string, clientWrapper: HttpClientWrapper, deepHealthUrl?: string | undefined | null, deploymentHealthPath?: string | undefined | null, healthCheckIntervalS?: number | undefined | null, healthCheckTimeoutS?: number | undefined | null, healthCheckRetries?: number | undefined | null, healthFailOnFirst?: boolean | undefined | null, deploymentTimeoutIsNoVote?: boolean | undefined | null, deepTimeoutIsNoVote?: boolean | undefined | null)
}
export declare class EndpointPool {
  constructor(endpoints: Array<Endpoint>, endpointWeights?: Array<number> | undefined | null)
}
export declare class PerformanceClient {
  constructor(baseUrl: string, apiKey?: string | undefined | null, httpVersion?: number | undefined | null, clientWrapper?: HttpClientWrapper | undefined | null, proxy?: string | undefined | null, endpointPool?: EndpointPool | undefined | null)
  getClientWrapper(): HttpClientWrapper
  embed(input: Array<string>, model: string, encodingFormat?: string | undefined | null, dimensions?: number | undefined | null, user?: string | undefined | null, preference?: RequestProcessingPreference | undefined | null): Promise<any>
  rerank(query: string, texts: Array<string>, rawScores?: boolean | undefined | null, model?: string | undefined | null, returnText?: boolean | undefined | null, truncate?: boolean | undefined | null, truncationDirection?: string | undefined | null, preference?: RequestProcessingPreference | undefined | null): Promise<any>
  classify(inputs: Array<string>, model?: string | undefined | null, rawScores?: boolean | undefined | null, truncate?: boolean | undefined | null, truncationDirection?: string | undefined | null, preference?: RequestProcessingPreference | undefined | null): Promise<any>
  batchPost(urlPath: string, payloads: Array<JsonValue>, preference?: RequestProcessingPreference | undefined | null, method?: string | undefined | null): Promise<any>
}
