/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * User-facing configuration for request processing with budget percentages.
 * CancellationToken for cancelling async operations
 */
export declare class CancellationToken {
  /** Create a new cancellation token */
  constructor()
  /** Cancel all operations using this token */
  cancel(): void
  /** Check if cancellation has been requested */
  get isCancelled(): boolean
}

export declare class HttpClientWrapper {
  constructor(httpVersion?: number | undefined | null)
}

export declare class PerformanceClient {
  constructor(baseUrl: string, apiKey?: string | undefined | null, httpVersion?: number | undefined | null, clientWrapper?: HttpClientWrapper | undefined | null)
  getClientWrapper(): HttpClientWrapper
  embed(input: Array<string>, model: string, encodingFormat?: string | undefined | null, dimensions?: number | undefined | null, user?: string | undefined | null, preference?: RequestProcessingPreference | undefined | null): Promise<any>
  rerank(query: string, texts: Array<string>, rawScores?: boolean | undefined | null, model?: string | undefined | null, returnText?: boolean | undefined | null, truncate?: boolean | undefined | null, truncationDirection?: string | undefined | null, preference?: RequestProcessingPreference | undefined | null): Promise<any>
  classify(inputs: Array<string>, model?: string | undefined | null, rawScores?: boolean | undefined | null, truncate?: boolean | undefined | null, truncationDirection?: string | undefined | null, preference?: RequestProcessingPreference | undefined | null): Promise<any>
  batchPost(urlPath: string, payloads: Array<JsonValue>, preference?: RequestProcessingPreference | undefined | null, customHeaders?: Record<string, string> | undefined | null, method?: string | undefined | null): Promise<any>
}

/** Provides sensible defaults and getters for all properties. */
export declare class RequestProcessingPreference {
  constructor(maxConcurrentRequests?: number | undefined | null, batchSize?: number | undefined | null, timeoutS?: number | undefined | null, maxCharsPerRequest?: number | undefined | null, hedgeDelay?: number | undefined | null, totalTimeoutS?: number | undefined | null, hedgeBudgetPct?: number | undefined | null, retryBudgetPct?: number | undefined | null, maxRetries?: number | undefined | null, initialBackoffMs?: number | undefined | null, cancelToken?: CancellationToken | undefined | null, primaryApiKeyOverride?: string | undefined | null)
  get maxConcurrentRequests(): number
  get batchSize(): number
  get timeoutS(): number
  get maxCharsPerRequest(): number | null
  get hedgeDelay(): number | null
  get totalTimeoutS(): number | null
  get hedgeBudgetPct(): number
  get retryBudgetPct(): number
  get maxRetries(): number
  get initialBackoffMs(): number
  get primaryApiKeyOverride(): string | null
}
