// Package entry point: the native binding (binding.js, generated by `napi build`), with each
// call joining the caller's active OpenTelemetry span when @opentelemetry/api is installed and
// the call's preference doesn't already name a parent. The context is captured here, at the
// JavaScript call boundary, because the Rust core has no view of JavaScript async context.
'use strict'

const binding = require('./binding.js')

let otel = null
try {
  otel = require('@opentelemetry/api')
} catch {
  // Optional peer dependency: without it, calls carry no ambient trace context.
}

function activeTraceContext() {
  if (!otel) {
    return null
  }
  try {
    const spanContext = otel.trace.getSpanContext(otel.context.active())
    if (!spanContext || !otel.isSpanContextValid(spanContext)) {
      return null
    }
    const flags = (spanContext.traceFlags & 0xff).toString(16).padStart(2, '0')
    const tracestate = spanContext.traceState ? spanContext.traceState.serialize() : ''
    return {
      traceparent: `00-${spanContext.traceId}-${spanContext.spanId}-${flags}`,
      tracestate: tracestate || undefined,
    }
  } catch {
    // Tracing must never break a request.
    return null
  }
}

// Position of the RequestProcessingPreference argument in each method that sends requests.
const PREFERENCE_ARGUMENT = { embed: 5, rerank: 7, classify: 5, batchPost: 2 }

class PerformanceClient extends binding.PerformanceClient {}

for (const [method, index] of Object.entries(PREFERENCE_ARGUMENT)) {
  const native = binding.PerformanceClient.prototype[method]
  Object.defineProperty(PerformanceClient.prototype, method, {
    configurable: true,
    writable: true,
    value: function (...args) {
      const context = activeTraceContext()
      if (context) {
        const preference = args[index] ?? new binding.RequestProcessingPreference()
        if (!preference.hasExplicitTraceContext) {
          args[index] = preference.withTraceContext(context.traceparent, context.tracestate)
        }
      }
      return native.apply(this, args)
    },
  })
}

// Spelled as `...require()` so Node's CommonJS lexer can list the binding's names for ESM
// `import { ... }`; spreading the `binding` variable would hide them.
module.exports = {
  ...require('./binding.js'),
  PerformanceClient,
}
