data_dir: data
input_type: Any
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_type: custom
model_metadata: {}
model_module_dir: model
python_version: py39
requirements:
  - torchvision==0.8.2
  - git+https://github.com/openai/CLIP.git
resources:
  cpu: 500m
  memory: 8Gi
  use_gpu: false
spec_version: '2.0'
system_packages: []
