root: ./docs

​structure:
    readme: ../README.md
    summary: SUMMARY.md​

redirects:
    create/huggingface: develop/README.md
    create/lightgbm: develop/README.md
    create/mlflow: develop/README.md
    create/pytorch: develop/README.md
    create/sklearn: develop/README.md
    create/tensorflow: develop/README.md
    create/xgboost: develop/README.md
    create/manual: develop/README.md
    e2e: quickstart.md
