data_dir: data
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: null
model_type: custom
python_version: py39
requirements:
  - tensorflow==2.7.1
  - tensorflow-hub==0.12.0
  - pillow==9.0.1
resources:
  cpu: 500m
  memory: 512Mi
  use_gpu: false
spec_version: '2.0'
system_packages: []
