bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: Flan-T5 XL
model_type: custom
python_version: py39
requirements:
  - transformers
  - torch
  - accelerate
  - sentencepiece
resources:
  cpu: '3'
  memory: 14Gi
  use_gpu: true
secrets:
  hf_access_token: null
spec_version: '2.0'
system_packages: []
live_reload: false
