name: Test truss-transfer import

on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: truss-transfer

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Create venv
        run: python3 -m venv .venv
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          command: develop
          sccache: 'true'
      - name: Try import truss truss-transfer-maturin-publish
        run: |
          source .venv/bin/activate
          python -c "import truss_transfer;print(truss_transfer.__version__)"
