build:
  arguments:
    endpoint: generate
    model_id: facebook/opt-125m
  model_server: TGI
environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: Test TGI
python_version: py39
requirements: []
hf_cache:
- repo_id: facebook/opt-125m
  ignore_patterns:
    - "*.h5"
    - "*.msgpack"
resources:
  accelerator: null
  cpu: '1'
  memory: 2Gi
  use_gpu: false
secrets: {}
system_packages: []
