environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: test
python_version: py39
requirements:
- transformers
- torch
model_cache:
- repo_id: julien-c/EsperBERTo-small
  revision: "2439f60ef33a0d46d85da5001d52aeda5b00ce9f"
  ignore_patterns:
    - "*.bin"
    - "*.msgpack"
resources:
  accelerator: null
  cpu: '2'
  memory: 2Gi
  use_gpu: false
secrets: {}
system_packages: []
