model_name: qwen-3-tts-streaming-base-12hz-1.7b
python_version: py312
model_metadata:
  repo_id: Qwen/Qwen3-TTS-12Hz-1.7B-Base
environment_variables:
  VLLM_ALLOW_LONG_MAX_MODEL_LEN: 1
weights:
  - source: "hf://Qwen/Qwen3-TTS-12Hz-1.7B-Base@main"
    mount_location: "/models/Qwen3-TTS-12Hz-1.7B-Base"
base_image:
  image: baseten/vllm-omni:v0.19.0-rc0
secrets:
  hf_access_token: null
system_packages:
  - sox
  - ffmpeg
docker_server:
  start_command: sh -c 'chmod +x /app/data/do.sh && /app/data/do.sh /models/Qwen3-TTS-12Hz-1.7B-Base'
  readiness_endpoint: /health
  liveness_endpoint: /health
  predict_endpoint: /v1/audio/speech/stream
  server_port: 8091
resources:
  accelerator: H100
  use_gpu: true
runtime:
  predict_concurrency: 64
  transport:
    kind: websocket
