build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: example-trace
python_version: py39
requirements:
- truss @ git+https://github.com/basetenlabs/truss.git@ae2d150052a892a7a625681349a0df09e91a1627
resources:
  accelerator: null
  cpu: '1'
  memory: 2Gi
  use_gpu: false
secrets: {}
system_packages: []
