base_image:
  image: python:3.11-slim
  python_executable_path: ''
environment_variables: {}
external_package_dirs: []
model_metadata:
  slay_metadata:
    model_config:
      arbitrary_types_allowed: true
    stub_cls_to_url:
      GenerateData: https://model-6wgveg4w.api.baseten.co/production
      SplitText: https://model-vq0p1673.api.baseten.co/production
      TextToNum: https://model-4w52o9vw.api.baseten.co/production
    user_config: null
model_name: Workflow
python_version: '3.11'
requirements: []
requirements_file: requirements.txt
resources:
  accelerator: null
  cpu: '1'
  memory: 2Gi
  use_gpu: false
secrets:
  baseten_api_key: BASETEN_API_KEY
system_packages: []
