name: "Setup Python"
description: "setups python, poetry and associated cache"


runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: '3.9.21'

    - name: Get full Python version
      id: full-python-version
      shell: bash
      run: echo "version=$(python -c 'import sys; print(\"-\".join(str(v) for v in sys.version_info))')" >> $GITHUB_ENV

    - name: Install Poetry with Debug Output
      env:
        POETRY_VERBOSE: 1
      run: |
        set -x
        curl -sSL https://install.python-poetry.org | python3 -v -
      shell: bash

    - name: Configure poetry
      run: poetry config virtualenvs.in-project true
      shell: bash

    - name: Set up cache
      uses: actions/cache@v4
      id: cache
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ env.version }}-${{ hashFiles('**/poetry.lock') }}

    - name: Ensure cache is healthy
      if: steps.cache.outputs.cache-hit == 'true'
      run: timeout 10s poetry run pip --version || rm -rf .venv
      shell: bash
