# System-wide configuration constants
import os

# Worker Configuration
MAX_TRANSCRIPTION_WORKERS = 4
MAX_DIARIZATION_WORKERS = 20
MAX_ASSIGNMENT_WORKERS = 20

# Queue Configuration
TRANSCRIPTION_QUEUE_SIZE = 100
DIARIZATION_QUEUE_SIZE = 500
ASSIGNMENT_QUEUE_SIZE = 50

# Resource Configuration
MAX_AUDIO_BUFFER_DURATION = 30.0
PARTIAL_TRANSCRIPT_INTERVAL = 1.0
DIARIZATION_WAIT_TIMEOUT = 30.0
CLEANUP_TIMEOUT = 10.0

# Whisper Configuration
DEFAULT_WHISPER_MODEL = "whisper-large-v3"
WHISPER_SAMPLE_RATE = 16000

# Streaming
DEFAULT_CHUNK_SIZE = 512

# VAD Configuration
VAD_LOOKBACK_WINDOW_SECS = 0.5

# Diarization Configuration
DIARIZATION_DURATION = 5.0
DIARIZATION_STEP = 0.5
DIARIZATION_PATCH_COLLAR = 0.05
MIN_SEGMENT_DURATION = 0.5
DIARIZATION_INTERVAL = 10.0  # number of seconds to wait before queuing another diarization task

assert (
    DIARIZATION_INTERVAL > DIARIZATION_DURATION
), "DIARIZATION_INTERVAL must be greater than DIARIZATION_DURATION"

# Error Configuration
MAX_DIARIZATION_WAIT_TIME = 30.0
DIARIZATION_WAIT_INTERVAL = 0.1

# Synchronization Configuration
MAX_DIARIZATION_WAIT_TIME = 30.0
DIARIZATION_WAIT_INTERVAL = 0.1

# Logging Configuration
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")

# worker types
TRANSCRIPTION_WORKER_TYPE = "TRANSCRIPTION_WORKER"
DIARIZATION_WORKER_TYPE = "DIARIZATION_WORKER"
ASSIGNMENT_WORKER_TYPE = "ASSIGNMENT_WORKER"
