base_image:
  image: python:3.11-slim
  python_executable_path: ''
environment_variables: {}
external_package_dirs: []
model_metadata:
  slay_metadata:
    stub_cls_to_url:
      GenerateData: http://app.baseten.co/models/GenerateData/predict
      SplitText: http://app.baseten.co/models/SplitText/predict
    user_config:
      hf_model_name: EleutherAI/mistral-6.7B
model_name: MistralLLM
python_version: '3.11'
requirements: []
requirements_file: requirements.txt
resources:
  accelerator: null
  cpu: '1'
  memory: 2Gi
  use_gpu: false
secrets:
  baseten_api_key: BASETEN_API_KEY
system_packages: []
