data_dir: data
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
model_class_filename: model.py
model_class_name: GPTJTransformerModel
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: null
model_type: custom
python_version: py39
requirements:
  - torch==1.11.0
  - transformers==4.18.0
  - accelerate==0.10.0
resources:
  use_gpu: true
secrets: {}
spec_version: '2.0'
system_packages: []
