bundled_packages_dir: packages
description: null
environment_variables: {}
examples_filename: examples.yaml
input_type: Any
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: Whisper
model_type: custom
python_version: py39
requirements:
- git+https://github.com/openai/whisper.git
- --extra-index-url https://download.pytorch.org/whl/cu113
- requests
resources:
  cpu: 500m
  memory: 3Gi
  use_gpu: true
secrets: {}
spec_version: 2.0
system_packages:
- ffmpeg
