environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: test
python_version: py39
requirements:
- transformers
- torch
hf_cache:
- repo_id: julien-c/EsperBERTo-small
  ignore_patterns:
    - "*.bin"
    - "*.msgpack"
resources:
  accelerator: null
  cpu: '2'
  memory: 2Gi
  use_gpu: false
secrets: {}
system_packages: []
