apply_library_patches: true
base_image: null
build:
  arguments: {}
  model_server: TrussServer
bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
examples_filename: examples.yaml
external_data: null
external_package_dirs: []
input_type: Any
live_reload: false
model_cache: []
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: foobar
model_type: Model
python_version: py39
requirements: []
requirements_file: null
resources:
  accelerator: null
  cpu: '1'
  memory: 2Gi
  use_gpu: false
runtime:
  num_workers: 1
  predict_concurrency: 1
secrets: {}
spec_version: '2.0'
system_packages: []
train:
  resources:
    accelerator: null
    cpu: '1'
    memory: 2Gi
    use_gpu: false
  training_class_filename: train.py
  training_class_name: Train
  training_module_dir: train
  variables: {}
