bundled_packages_dir: packages
data_dir: data
description: null
environment_variables: {}
examples_filename: examples.yaml
external_package_dirs:
- ../shared/
input_type: Any
live_reload: false
model_class_filename: model.py
model_class_name: Model
model_framework: custom
model_metadata: {}
model_module_dir: model
model_name: null
model_type: custom
python_version: py39
requirements:
- opencv-contrib-python
- controlnet_aux
- diffusers
- transformers
- accelerate
- xformers
resources:
  accelerator: A10G
  cpu: "8"
  memory: 30Gi
  use_gpu: true
secrets: {}
spec_version: '2.0'
system_packages:
- ffmpeg
