name: Reusable Integration Tests

on:
  workflow_call:

jobs:
  truss-integration-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        split_group: ["1", "2", "3", "4", "5"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python/
      - run: sudo mkdir -p /bptr && sudo chown $(whoami):$(whoami) /bptr
      - run: poetry install --with=dev,dev-server --extras=all
      - run: |
          poetry run pytest truss/tests \
          --durations=0 -m 'integration' \
          --junitxml=report-${{ matrix.split_group }}.xml \
          --splits 5 --group ${{ matrix.split_group }} \

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: "report-${{ matrix.split_group }}.xml"

  chains-integration-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        split_group: ["1"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python/
      - run: sudo mkdir -p /bptr && sudo chown $(whoami):$(whoami) /bptr
      - run: poetry install --with=dev,dev-server --extras=all
      - run: |
          poetry run pytest truss-chains/tests \
          --durations=0 -m 'integration' \
          --junitxml=report.xml \
          -s --log-cli-level=INFO \

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: "report.xml"
