name: Integration Tests

on:
  workflow_call:
    inputs:
      build-and-push-truss-base-images-if-needed-result:
        required: true
        type: string

jobs:
  integration-tests:
    if: ${{ !failure() && !cancelled() && (build-and-push-truss-base-images-if-needed-result == 'success' || build-and-push-truss-base-images-if-needed-result == 'skipped') }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        split_group: ["1", "2", "3", "4", "5"]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python/
      - run: poetry install
      - run: poetry run pytest truss/tests --durations=0 -m 'integration' --splits 5 --group ${{ matrix.split_group }} -k "not test_requirements_pydantic[1]"

  integration-tests-pydantic-v1:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python/
      - run: poetry install
      - run: poetry run pytest truss/tests/test_model_inference.py::test_requirements_pydantic[1]

  chain-integration-tests:
    if: ${{ !failure() && !cancelled() && (build-and-push-truss-base-images-if-needed-result == 'success' || build-and-push-truss-base-images-if-needed-result == 'skipped') }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python/
      - run: poetry install
      - run: poetry run pytest truss-chains/tests -s --log-cli-level=INFO  --durations=0 -m 'integration'
