name: Build Context Builder Image

on:
  workflow_dispatch:
    inputs:
      target_platforms:
        description: 'Select target platforms. NOTE: Only change default if performing local testing.'
        required: false
        default: 'linux/amd64,linux/arm64'
        type: choice
        options:
          - linux/amd64
          - linux/arm64
          - linux/amd64,linux/arm64

jobs:
  detect-version:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.versions.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          # We need to use a different github token because GITHUB_TOKEN cannot trigger a workflow from another
          token: ${{secrets.BASETENBOT_GITHUB_TOKEN}}
          fetch-depth: 2
      - run: curl -sSL https://install.python-poetry.org | python3 -
        shell: bash
      - id: versions
        run: |
          VERSION=$(poetry version | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  build-n-push-context-builder-image:
    runs-on: ubuntu-22.04
    needs: [detect-version]
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Generate image name
      id: generate_image_tag
      run: echo "tag=baseten/truss-context-builder:v${{ needs.detect-version.outputs.version }}" >> $GITHUB_OUTPUT

    - name: Check if image already exists
      run: |
        if docker manifest inspect ${{ steps.generate_image_tag.outputs.tag }} > /dev/null 2>&1; then
          echo "Context builder image with tag ${{ needs.detect-version.outputs.version }} already exists, please update pyproject.toml"
          exit 1
        fi

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: baseten/truss-context-builder

    - name: Docker Build
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./context_builder.Dockerfile
        push: true
        tags: ${{ steps.generate_image_tag.outputs.tag }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: ${{ github.event.inputs.target_platforms }}
