# .github/workflows/create-rc-release.yml
name: Create RC Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'RC version to release'
        required: true
        type: string

jobs:
  publish-rc-only:
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    steps:
      - name: Validate version format
        run: |
          VERSION="${{ github.event.inputs.version }}"
          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+rc[0-9]+$ ]]; then
            echo "❌ Invalid version format: $VERSION"
            echo "✅ Expected format: X.Y.ZrcN (e.g., 0.11.13rc1)"
            exit 1
          fi
          echo "✅ Version format is valid: $VERSION"
      - uses: ./.github/actions/setup-python/
      - name: Install packages
        run: uv sync --no-dev
      - name: Build
        run: uv build
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
