name: Truss CLI E2E tests

on:
  workflow_dispatch:
    inputs:
      truss_version:
        description: "The version of Truss to test"
        required: false
      leave_deployments:
        description: "If set, deployments are not deleted."
        required: false
        default: false
        type: boolean
jobs:
  test-chains:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Python
        uses: ./.github/actions/setup-python/
      - name: Install
        run: uv sync
      - name: Install Truss
        run: |
          python -m venv truss_env
          TRUSS_VERSION=${{ github.event.inputs.truss_version || 'latest' }}
          if [ "$TRUSS_VERSION" = "latest" ]; then
            echo "Installing the latest version of Truss"
            truss_env/bin/pip install truss
          else
            echo "Installing Truss version $TRUSS_VERSION"
            truss_env/bin/pip install truss==$TRUSS_VERSION
          fi
      - name: Run tests
        env:
          TRUSS_ENV_PATH: ${{ github.workspace }}/truss_env
        run: |
          BASETEN_API_KEY_STAGING="${{ secrets.BASETEN_API_KEY_STAGING }}" \
          LEAVE_DEPLOYMENTS="${{ github.event.inputs.leave_deployments }}" \
          uv run pytest smoketests \
          --durations=0 \
          --junitxml=report.xml \
          -s --log-cli-level=INFO
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: always()
        with:
           commit: ${{ github.sha }}
           report_paths: "report.xml"
