name: Test truss-transfer import

on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    working-directory: truss-transfer  # Keeps default for run commands

jobs:
  test-truss-transfer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Create venv
        run: python3 -m venv .venv
      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          working-directory: truss-transfer
          command: develop
          sccache: 'true'
      - name: Try import truss-transfer-maturin-publish
        run: |
          source .venv/bin/activate
          python -c "import truss_transfer; print(truss_transfer.__version__)"
      - name: Try download github file
        run: |
          sudo mkdir -p /bptr
          sudo chown $(whoami):$(whoami) /bptr
          cp ./exampe-bptr-manifest.json /bptr/exampe-bptr-manifest

          source .venv/bin/activate
          python -c "import truss_transfer; truss_transfer.lazy_data_resolve('./tmp_no_cache/test', 1)""
          export BASETEN_FS_ENABLED=True
          python -c "import truss_transfer; truss_transfer.lazy_data_resolve('./tmp_fs_enabled/test', 1)"
